export const WORK_STATUS_OPTIONS = ['To-Do', 'In-Progress', 'Done'];

export const QC_STATUS_OPTIONS = ['Pending', 'Passed QC', 'Rework'];

export const seedData = {
  roles: [
    { id: 'super-admin', name: 'Super Admin' },
    { id: 'owner', name: 'Owner' },
    { id: 'production-manager', name: 'Production Manager' },
    { id: 'foreman', name: 'Foreman' },
    { id: 'qc-inspector', name: 'QC Inspector' },
    { id: 'admin', name: 'Admin' },
  ],
  users: [
    { id: 'usr-super-admin', name: 'Super Admin SIMO', roleId: 'super-admin', site: 'HQ' },
    { id: 'usr-owner', name: 'Rina Wijaya', roleId: 'owner', site: 'Pabrik Utama, IKN' },
    { id: 'usr-pm', name: 'Budi Santoso', roleId: 'production-manager', site: 'Pabrik Utama, IKN' },
    { id: 'usr-foreman', name: 'Joko Anwar', roleId: 'foreman', site: 'Warehouse Line A' },
    { id: 'usr-qc', name: 'Siti Nurhaliza', roleId: 'qc-inspector', site: 'QC Bay 2' },
    { id: 'usr-admin', name: 'Dewi Lestari', roleId: 'admin', site: 'Control Room' },
  ],
  projects: [
    {
      id: 'prj-ikn-a',
      code: 'IKN-A',
      name: 'IKN Facade Package A',
      client: 'Nusantara Civic Center',
      dueDate: '2026-06-18',
      priority: 'High',
    },
    {
      id: 'prj-ikn-b',
      code: 'IKN-B',
      name: 'IKN Residential Tower B',
      client: 'Mugi Jaya Build',
      dueDate: '2026-06-24',
      priority: 'Medium',
    },
    {
      id: 'prj-sby-mall',
      code: 'SBY-M1',
      name: 'Surabaya Mall Retrofit',
      client: 'Surya Properti',
      dueDate: '2026-07-02',
      priority: 'Medium',
    },
  ],
  warehouses: [
    { id: 'wh-frame', code: 'WH-01', name: 'Frame Warehouse', category: 'Aluminium Frame' },
    { id: 'wh-glass', code: 'WH-02', name: 'Glass Warehouse', category: 'Tempered Glass' },
    { id: 'wh-profile', code: 'WH-03', name: 'Profile Warehouse', category: 'Custom Profile' },
    { id: 'wh-hardware', code: 'WH-04', name: 'Hardware Warehouse', category: 'Locks & Accessories' },
    { id: 'wh-packaging', code: 'WH-05', name: 'Packaging Warehouse', category: 'Packaging Material' },
  ],
  workItems: [
    {
      id: 'wi-001',
      projectId: 'prj-ikn-a',
      warehouseId: 'wh-frame',
      taskName: 'Cut and assemble frame set A',
      materialName: 'Aluminium Frame Type A',
      quantity: 120,
      unit: 'pcs',
      status: 'Done',
      qcStatus: 'Passed QC',
      readyToShip: true,
    },
    {
      id: 'wi-002',
      projectId: 'prj-ikn-a',
      warehouseId: 'wh-glass',
      taskName: 'Prepare tempered glass panels',
      materialName: 'Tempered Glass 8mm',
      quantity: 40,
      unit: 'pcs',
      status: 'In-Progress',
      qcStatus: 'Pending',
      readyToShip: false,
    },
    {
      id: 'wi-003',
      projectId: 'prj-ikn-a',
      warehouseId: 'wh-hardware',
      taskName: 'Pack lockset hardware',
      materialName: 'Window Lockset A',
      quantity: 120,
      unit: 'sets',
      status: 'To-Do',
      qcStatus: 'Pending',
      readyToShip: false,
    },
    {
      id: 'wi-004',
      projectId: 'prj-ikn-b',
      warehouseId: 'wh-profile',
      taskName: 'Machine custom mullion profile',
      materialName: 'Custom Mullion Profile',
      quantity: 72,
      unit: 'bars',
      status: 'In-Progress',
      qcStatus: 'Pending',
      readyToShip: false,
    },
    {
      id: 'wi-005',
      projectId: 'prj-ikn-b',
      warehouseId: 'wh-frame',
      taskName: 'Weld balcony frame batch',
      materialName: 'Balcony Frame B',
      quantity: 64,
      unit: 'pcs',
      status: 'Done',
      qcStatus: 'Rework',
      readyToShip: false,
    },
    {
      id: 'wi-006',
      projectId: 'prj-ikn-b',
      warehouseId: 'wh-packaging',
      taskName: 'Prepare export-safe packaging',
      materialName: 'Corner Guard Packaging',
      quantity: 360,
      unit: 'pcs',
      status: 'To-Do',
      qcStatus: 'Pending',
      readyToShip: false,
    },
    {
      id: 'wi-007',
      projectId: 'prj-sby-mall',
      warehouseId: 'wh-glass',
      taskName: 'Laminate storefront glass',
      materialName: 'Laminated Glass 10mm',
      quantity: 28,
      unit: 'pcs',
      status: 'Done',
      qcStatus: 'Passed QC',
      readyToShip: true,
    },
    {
      id: 'wi-008',
      projectId: 'prj-sby-mall',
      warehouseId: 'wh-hardware',
      taskName: 'Count hinge and handle kits',
      materialName: 'Door Hardware Kit',
      quantity: 56,
      unit: 'sets',
      status: 'In-Progress',
      qcStatus: 'Pending',
      readyToShip: false,
    },
  ],
  qcChecklists: [
    {
      id: 'qc-001',
      projectId: 'prj-ikn-a',
      warehouseId: 'wh-frame',
      workItemId: 'wi-001',
      materialName: 'Aluminium Frame Type A',
      length: 2200,
      width: 900,
      thickness: 2.5,
      qcStatus: 'Passed QC',
      notes: 'Dimension and finish accepted.',
      evidencePhoto: 'frame-a-batch-01.jpg',
      createdBy: 'Siti Nurhaliza',
      createdByRole: 'QC Inspector',
      createdAt: '2026-06-08 09:10:00',
    },
    {
      id: 'qc-002',
      projectId: 'prj-ikn-b',
      warehouseId: 'wh-frame',
      workItemId: 'wi-005',
      materialName: 'Balcony Frame B',
      length: 1800,
      width: 1100,
      thickness: 2.2,
      qcStatus: 'Rework',
      notes: 'Corner alignment needs correction before shipping.',
      evidencePhoto: 'balcony-frame-rework.jpg',
      createdBy: 'Siti Nurhaliza',
      createdByRole: 'QC Inspector',
      createdAt: '2026-06-08 10:05:00',
    },
  ],
  auditLogs: [
    {
      id: 'log-001',
      timestamp: '2026-06-08 10:05:00',
      user: 'Siti Nurhaliza',
      role: 'QC Inspector',
      action: 'INSERT',
      table: 'qc_checklists',
      recordId: 'qc-002',
      previousValue: '-',
      newValue: 'Rework',
      description: 'Submitted QC checklist for Balcony Frame B.',
    },
    {
      id: 'log-002',
      timestamp: '2026-06-08 09:40:00',
      user: 'Joko Anwar',
      role: 'Foreman',
      action: 'UPDATE',
      table: 'work_items',
      recordId: 'wi-004',
      previousValue: 'To-Do',
      newValue: 'In-Progress',
      description: 'Updated Custom Mullion Profile production status.',
    },
    {
      id: 'log-003',
      timestamp: '2026-06-08 09:10:00',
      user: 'Siti Nurhaliza',
      role: 'QC Inspector',
      action: 'INSERT',
      table: 'qc_checklists',
      recordId: 'qc-001',
      previousValue: '-',
      newValue: 'Passed QC',
      description: 'Submitted QC checklist for Aluminium Frame Type A.',
    },
    {
      id: 'log-004',
      timestamp: '2026-06-08 08:35:00',
      user: 'Budi Santoso',
      role: 'Production Manager',
      action: 'UPDATE',
      table: 'work_items',
      recordId: 'wi-001',
      previousValue: 'In-Progress',
      newValue: 'Done',
      description: 'Completed frame batch for IKN Facade Package A.',
    },
  ],
};

export function createInitialDemoState() {
  return JSON.parse(JSON.stringify(seedData));
}
