import { Router } from 'express';
import { all, get } from '../db/database.js';
import { writeAuditLog } from '../utils/auditLogger.js';
import { requireAuth } from '../utils/auth.js';
import { asyncHandler, HttpError, sendData } from '../utils/http.js';

const REPORTS = {
  'operational-summary': { title: 'Operational Summary Report', roles: ['Super Admin', 'Owner', 'Admin', 'Production Manager'] },
  production: { title: 'Production Report', roles: ['Super Admin', 'Owner', 'Admin', 'Production Manager', 'Foreman'] },
  qc: { title: 'QC Report', roles: ['Super Admin', 'Owner', 'Admin', 'Production Manager', 'QC Inspector'] },
  logistics: { title: 'Logistics Report', roles: ['Super Admin', 'Owner', 'Admin', 'Production Manager'] },
  audit: { title: 'Audit Activity Report', roles: ['Super Admin', 'Owner', 'Admin', 'Production Manager'] },
};

function parsePeriod(query) {
  const startDate = String(query.startDate || '').trim();
  const endDate = String(query.endDate || '').trim();
  if (!/^\d{4}-\d{2}-\d{2}$/.test(startDate) || !/^\d{4}-\d{2}-\d{2}$/.test(endDate) || startDate > endDate) {
    throw new HttpError(400, 'INVALID_REPORT_PERIOD', 'Select a valid report period.');
  }
  return { startDate, endDate, startDateTime: `${startDate}T00:00:00.000Z`, endDateTime: `${endDate}T23:59:59.999Z` };
}

function requireReport(type, roleName) {
  const report = REPORTS[type];
  if (!report) throw new HttpError(404, 'REPORT_NOT_FOUND', 'Report type not found.');
  if (!report.roles.includes(roleName)) throw new HttpError(403, 'FORBIDDEN', 'This role cannot access the selected report.');
  return report;
}

function csvCell(value) {
  return `"${String(value ?? '').replaceAll('"', '""')}"`;
}

function toCsv(preview) {
  const lines = [
    ['Report', preview.title],
    ['Period', `${preview.period.startDate} to ${preview.period.endDate}`],
    ['Generated By', preview.generatedBy.name],
    ['Generated Role', preview.generatedBy.roleName],
    ['Generated At', preview.generatedAt],
    ['Row Count', preview.rowCount],
    [],
    preview.columns,
    ...preview.rows.map((row) => preview.columns.map((column) => row[column] ?? '')),
  ];
  return lines.map((line) => line.map(csvCell).join(',')).join('\n');
}


function pdfEscape(value) {
  return String(value ?? '').replaceAll('\\', '\\\\').replaceAll('(', '\\(').replaceAll(')', '\\)').slice(0, 110);
}

function wrapText(value, width = 92) {
  const words = String(value ?? '').replace(/\s+/g, ' ').split(' ');
  const lines = [];
  let line = '';
  for (const word of words) {
    if ((line + ' ' + word).trim().length > width) {
      if (line) lines.push(line);
      line = word;
    } else {
      line = `${line} ${word}`.trim();
    }
  }
  if (line) lines.push(line);
  return lines.length ? lines : ['-'];
}

function toPdf(preview) {
  const pageLines = [
    'SIMO Mugi Jaya',
    preview.title,
    `Period: ${preview.period.startDate} to ${preview.period.endDate}`,
    `Generated by: ${preview.generatedBy.name} (${preview.generatedBy.roleName})`,
    `Generated at: ${preview.generatedAt}`,
    `Rows: ${preview.rowCount}`,
    '',
    'Summary',
    ...Object.entries(preview.summary || {}).flatMap(([key, value]) => wrapText(`${key}: ${typeof value === 'object' ? JSON.stringify(value) : value}`)),
    '',
    'Preview Rows',
    ...preview.rows.slice(0, 24).flatMap((row, index) => wrapText(`${index + 1}. ${preview.columns.map((column) => `${column}: ${row[column] ?? '-'}`).join(' | ')}`)),
  ].slice(0, 58);

  const stream = [
    'BT',
    '/F1 16 Tf',
    '50 790 Td',
    `(${pdfEscape(pageLines[0])}) Tj`,
    '/F1 10 Tf',
    ...pageLines.slice(1).flatMap((line) => ['0 -14 Td', `(${pdfEscape(line)}) Tj`]),
    'ET',
  ].join('\n');

  const objects = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>',
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
    `<< /Length ${Buffer.byteLength(stream, 'utf8')} >>\nstream\n${stream}\nendstream`,
  ];

  let pdf = '%PDF-1.4\n';
  const offsets = [0];
  objects.forEach((object, index) => {
    offsets.push(Buffer.byteLength(pdf, 'utf8'));
    pdf += `${index + 1} 0 obj\n${object}\nendobj\n`;
  });
  const xrefOffset = Buffer.byteLength(pdf, 'utf8');
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  pdf += offsets.slice(1).map((offset) => `${String(offset).padStart(10, '0')} 00000 n \n`).join('');
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;
  return Buffer.from(pdf, 'utf8');
}

function summarizeCounts(rows, key) {
  return rows.reduce((counts, row) => {
    const value = row[key] || 'Unknown';
    counts[value] = (counts[value] || 0) + 1;
    return counts;
  }, {});
}

async function buildRows(db, type, period) {
  if (type === 'production') {
    return all(db, `SELECT p.code AS project, w.code AS warehouse, wi.name AS work_item, wi.category, wi.material_name, wi.quantity, wi.unit, wi.status, wi.qc_status, CASE WHEN wi.ready_to_ship = 1 THEN 'Ready' ELSE 'Not Ready' END AS shipping_status, wi.updated_at
      FROM work_items wi JOIN projects p ON p.id = wi.project_id JOIN warehouses w ON w.id = wi.warehouse_id
      WHERE wi.updated_at BETWEEN ? AND ? ORDER BY p.code, w.code, wi.name`, [period.startDateTime, period.endDateTime]);
  }
  if (type === 'qc') {
    return all(db, `SELECT p.code AS project, w.code AS warehouse, wi.name AS work_item, qc.material_name, qc.qc_status, qc.inspector_name, qc.notes, qc.created_at
      FROM qc_checklists qc JOIN projects p ON p.id = qc.project_id JOIN warehouses w ON w.id = qc.warehouse_id JOIN work_items wi ON wi.id = qc.work_item_id
      WHERE qc.created_at BETWEEN ? AND ? ORDER BY qc.created_at DESC`, [period.startDateTime, period.endDateTime]);
  }
  if (type === 'logistics') {
    return all(db, `SELECT lm.manifest_number, COALESCE(p.code, '-') AS project, lm.driver_name, lm.vehicle_plate, lm.origin, lm.destination, lm.delivery_status, lm.departure_time, lm.arrival_time, lm.updated_at
      FROM logistics_manifests lm LEFT JOIN projects p ON p.id = lm.project_id
      WHERE lm.created_at BETWEEN ? AND ? OR lm.updated_at BETWEEN ? AND ? ORDER BY lm.updated_at DESC`, [period.startDateTime, period.endDateTime, period.startDateTime, period.endDateTime]);
  }
  if (type === 'audit') {
    return all(db, `SELECT created_at, user_name, role_name, module, action_type, action, entity_type, entity_id, description
      FROM audit_logs WHERE created_at BETWEEN ? AND ? ORDER BY created_at DESC, id DESC`, [period.startDateTime, period.endDateTime]);
  }

  const [projects, warehouses, workItems, qcRows, logisticsRows, auditRows] = await Promise.all([
    get(db, 'SELECT COUNT(*) AS count FROM projects'),
    get(db, 'SELECT COUNT(*) AS count FROM warehouses'),
    all(db, 'SELECT status FROM work_items WHERE updated_at BETWEEN ? AND ?', [period.startDateTime, period.endDateTime]),
    all(db, 'SELECT qc_status FROM qc_checklists WHERE created_at BETWEEN ? AND ?', [period.startDateTime, period.endDateTime]),
    all(db, 'SELECT delivery_status FROM logistics_manifests WHERE created_at BETWEEN ? AND ? OR updated_at BETWEEN ? AND ?', [period.startDateTime, period.endDateTime, period.startDateTime, period.endDateTime]),
    get(db, 'SELECT COUNT(*) AS count FROM audit_logs WHERE created_at BETWEEN ? AND ?', [period.startDateTime, period.endDateTime]),
  ]);
  return [
    { metric: 'Total projects', value: projects.count, detail: 'All project records' },
    { metric: 'Total warehouses', value: warehouses.count, detail: 'All warehouse records' },
    { metric: 'Work items in period', value: workItems.length, detail: JSON.stringify(summarizeCounts(workItems, 'status')) },
    { metric: 'QC records in period', value: qcRows.length, detail: JSON.stringify(summarizeCounts(qcRows, 'qc_status')) },
    { metric: 'Logistics manifests in period', value: logisticsRows.length, detail: JSON.stringify(summarizeCounts(logisticsRows, 'delivery_status')) },
    { metric: 'Audit actions in period', value: auditRows.count, detail: 'Recorded audit events' },
  ];
}

function buildSummary(rows, type) {
  if (type === 'production') return summarizeCounts(rows, 'status');
  if (type === 'qc') return summarizeCounts(rows, 'qc_status');
  if (type === 'logistics') return summarizeCounts(rows, 'delivery_status');
  if (type === 'audit') return summarizeCounts(rows, 'module');
  return Object.fromEntries(rows.map((row) => [row.metric, row.value]));
}

async function buildPreview(db, type, period, user) {
  const report = requireReport(type, user.roleName);
  const rows = await buildRows(db, type, period);
  return {
    type,
    title: report.title,
    period: { startDate: period.startDate, endDate: period.endDate },
    generatedBy: { id: user.id, name: user.name, roleName: user.roleName },
    generatedAt: new Date().toISOString(),
    summary: buildSummary(rows, type),
    rowCount: rows.length,
    columns: rows[0] ? Object.keys(rows[0]) : ['message'],
    rows: rows.slice(0, 100),
  };
}

async function auditReport(db, req, actionType, preview) {
  await writeAuditLog(db, {
    actor: { id: req.user.id, name: req.user.name, roleName: req.user.roleName },
    module: 'Reports',
    actionType,
    action: actionType === 'EXPORT_REPORT_CSV' ? 'Export report CSV' : actionType === 'EXPORT_REPORT_PDF' ? 'Export report PDF' : 'Preview report',
    entityType: 'Report',
    entityId: preview.type,
    tableName: 'reports',
    previousValue: null,
    newValue: JSON.stringify({ type: preview.type, period: preview.period, rowCount: preview.rowCount }),
    description: `${preview.title} ${actionType === 'EXPORT_REPORT_CSV' ? 'exported as CSV' : actionType === 'EXPORT_REPORT_PDF' ? 'exported as PDF' : 'previewed'}.`,
  });
}

export function createReportsRouter(db) {
  const router = Router();
  router.use(requireAuth);

  router.get('/types', asyncHandler(async (req, res) => {
    const reports = Object.entries(REPORTS)
      .filter(([, report]) => report.roles.includes(req.user.roleName))
      .map(([id, report]) => ({ id, title: report.title, formats: ['csv', 'pdf'], roles: report.roles }));
    sendData(res, reports, { meta: { count: reports.length } });
  }));

  router.get('/:type/preview', asyncHandler(async (req, res) => {
    const preview = await buildPreview(db, req.params.type, parsePeriod(req.query), req.user);
    sendData(res, preview);
  }));

  router.get('/:type/export.csv', asyncHandler(async (req, res) => {
    const period = parsePeriod(req.query);
    const preview = await buildPreview(db, req.params.type, period, req.user);
    await auditReport(db, req, 'EXPORT_REPORT_CSV', preview);
    res.setHeader('Content-Type', 'text/csv; charset=utf-8');
    res.setHeader('Content-Disposition', `attachment; filename="${preview.type}-${period.startDate}-to-${period.endDate}.csv"`);
    res.status(200).send(toCsv(preview));
  }));


  router.get('/:type/export.pdf', asyncHandler(async (req, res) => {
    const period = parsePeriod(req.query);
    const preview = await buildPreview(db, req.params.type, period, req.user);
    await auditReport(db, req, 'EXPORT_REPORT_PDF', preview);
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${preview.type}-${period.startDate}-to-${period.endDate}.pdf"`);
    res.status(200).send(toPdf(preview));
  }));

  return router;
}
